/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as YearRouteImport } from './routes/year'
import { Route as TitlesIdRouteImport } from './routes/titles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const YearRoute = YearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => rootRouteImport,
} as any)
const TitlesIdRoute = TitlesIdRouteImport.update({
  id: '/titles/$id',
  path: '/titles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/year': typeof YearRoute
  '/titles/$id': typeof TitlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/year': typeof YearRoute
  '/titles/$id': typeof TitlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/year': typeof YearRoute
  '/titles/$id': typeof TitlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/login' | '/settings' | '/year' | '/titles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/login' | '/settings' | '/year' | '/titles/$id'
  id:
    '__root__' | '/' | '/add' | '/login' | '/settings' | '/year' | '/titles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  YearRoute: typeof YearRoute
  TitlesIdRoute: typeof TitlesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year': {
      id: '/year'
      path: '/year'
      fullPath: '/year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titles/$id': {
      id: '/titles/$id'
      path: '/titles/$id'
      fullPath: '/titles/$id'
      preLoaderRoute: typeof TitlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  YearRoute: YearRoute,
  TitlesIdRoute: TitlesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
